### PR TITLE
Add publish info to readme

### PR DESCRIPTION
**Pull request by ndrjkvc**
Adds info about publishing and usage of the adjusted plugins

### CODE REVIEW

**Review by szist — APPROVED** [review]
If there was a way to define/override the tag suffix/prefix for publishing feature branch builds, that would be nice and would be good to document that.

**Comment by ndrjkvc** [comment]
> If there was a way to define/override the tag suffix/prefix for publishing feature branch builds, that would be nice and would be good to document that.

It looks like it takes name and version from package.json. 
The version has to be valid semver, but you can change the name to pretty much anything. I have not tested changing the name though.
The `-gitpkg` at the end is hardcoded.

**Comment by szist** [comment]
that's fine :) also if you replaced the github url into the `github:owner/project#tag` would be good.

**Comment by ndrjkvc** [comment]
So I tested changing the name in package.json. It changes the git tag name. Also, the change does not have to be committed.

**Comment by ndrjkvc** [comment]
But changing the name will also change the name under which it will be installed if you do not specify it, if I understand that correctly.

**Review by szist — APPROVED** [review]
what happened with that extra formatting changes? :)

**Pull request merged**
